######################################################################
##
## Filename: vga_top_vga_top_sch_tb.udo
## Created on: Sat Jun 06 16:52:10 China Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
